#############################################################################
# Makefile for building: qlc
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sun Dec 12 05:55:08 2010
# Project:  qlc.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile qlc.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-engine \
		sub-ui \
		sub-fixtures \
		sub-inputprofiles \
		sub-fixtureeditor \
		sub-etc \
		sub-docs \
		sub-plugins

engine/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) engine/ || $(MKDIR) engine/ 
	cd engine/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/engine/engine.pro -o $(MAKEFILE)
sub-engine-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) engine/ || $(MKDIR) engine/ 
	cd engine/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/engine/engine.pro -o $(MAKEFILE)
sub-engine: engine/$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE)
sub-engine-make_default: engine/$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) 
sub-engine-make_first: engine/$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) first
sub-engine-all: engine/$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) all
sub-engine-clean: engine/$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) clean
sub-engine-distclean: engine/$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) distclean
sub-engine-install_subtargets: engine/$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) install
sub-engine-uninstall_subtargets: engine/$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) uninstall
ui/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ui/ || $(MKDIR) ui/ 
	cd ui/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/ui/ui.pro -o $(MAKEFILE)
sub-ui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ui/ || $(MKDIR) ui/ 
	cd ui/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/ui/ui.pro -o $(MAKEFILE)
sub-ui: ui/$(MAKEFILE) FORCE
	cd ui/ && $(MAKE) -f $(MAKEFILE)
sub-ui-make_default: ui/$(MAKEFILE) FORCE
	cd ui/ && $(MAKE) -f $(MAKEFILE) 
sub-ui-make_first: ui/$(MAKEFILE) FORCE
	cd ui/ && $(MAKE) -f $(MAKEFILE) first
sub-ui-all: ui/$(MAKEFILE) FORCE
	cd ui/ && $(MAKE) -f $(MAKEFILE) all
sub-ui-clean: ui/$(MAKEFILE) FORCE
	cd ui/ && $(MAKE) -f $(MAKEFILE) clean
sub-ui-distclean: ui/$(MAKEFILE) FORCE
	cd ui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-ui-install_subtargets: ui/$(MAKEFILE) FORCE
	cd ui/ && $(MAKE) -f $(MAKEFILE) install
sub-ui-uninstall_subtargets: ui/$(MAKEFILE) FORCE
	cd ui/ && $(MAKE) -f $(MAKEFILE) uninstall
fixtures/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) fixtures/ || $(MKDIR) fixtures/ 
	cd fixtures/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/fixtures/fixtures.pro -o $(MAKEFILE)
sub-fixtures-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) fixtures/ || $(MKDIR) fixtures/ 
	cd fixtures/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/fixtures/fixtures.pro -o $(MAKEFILE)
sub-fixtures: fixtures/$(MAKEFILE) FORCE
	cd fixtures/ && $(MAKE) -f $(MAKEFILE)
sub-fixtures-make_default: fixtures/$(MAKEFILE) FORCE
	cd fixtures/ && $(MAKE) -f $(MAKEFILE) 
sub-fixtures-make_first: fixtures/$(MAKEFILE) FORCE
	cd fixtures/ && $(MAKE) -f $(MAKEFILE) first
sub-fixtures-all: fixtures/$(MAKEFILE) FORCE
	cd fixtures/ && $(MAKE) -f $(MAKEFILE) all
sub-fixtures-clean: fixtures/$(MAKEFILE) FORCE
	cd fixtures/ && $(MAKE) -f $(MAKEFILE) clean
sub-fixtures-distclean: fixtures/$(MAKEFILE) FORCE
	cd fixtures/ && $(MAKE) -f $(MAKEFILE) distclean
sub-fixtures-install_subtargets: fixtures/$(MAKEFILE) FORCE
	cd fixtures/ && $(MAKE) -f $(MAKEFILE) install
sub-fixtures-uninstall_subtargets: fixtures/$(MAKEFILE) FORCE
	cd fixtures/ && $(MAKE) -f $(MAKEFILE) uninstall
inputprofiles/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) inputprofiles/ || $(MKDIR) inputprofiles/ 
	cd inputprofiles/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/inputprofiles/inputprofiles.pro -o $(MAKEFILE)
sub-inputprofiles-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) inputprofiles/ || $(MKDIR) inputprofiles/ 
	cd inputprofiles/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/inputprofiles/inputprofiles.pro -o $(MAKEFILE)
sub-inputprofiles: inputprofiles/$(MAKEFILE) FORCE
	cd inputprofiles/ && $(MAKE) -f $(MAKEFILE)
sub-inputprofiles-make_default: inputprofiles/$(MAKEFILE) FORCE
	cd inputprofiles/ && $(MAKE) -f $(MAKEFILE) 
sub-inputprofiles-make_first: inputprofiles/$(MAKEFILE) FORCE
	cd inputprofiles/ && $(MAKE) -f $(MAKEFILE) first
sub-inputprofiles-all: inputprofiles/$(MAKEFILE) FORCE
	cd inputprofiles/ && $(MAKE) -f $(MAKEFILE) all
sub-inputprofiles-clean: inputprofiles/$(MAKEFILE) FORCE
	cd inputprofiles/ && $(MAKE) -f $(MAKEFILE) clean
sub-inputprofiles-distclean: inputprofiles/$(MAKEFILE) FORCE
	cd inputprofiles/ && $(MAKE) -f $(MAKEFILE) distclean
sub-inputprofiles-install_subtargets: inputprofiles/$(MAKEFILE) FORCE
	cd inputprofiles/ && $(MAKE) -f $(MAKEFILE) install
sub-inputprofiles-uninstall_subtargets: inputprofiles/$(MAKEFILE) FORCE
	cd inputprofiles/ && $(MAKE) -f $(MAKEFILE) uninstall
fixtureeditor/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) fixtureeditor/ || $(MKDIR) fixtureeditor/ 
	cd fixtureeditor/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/fixtureeditor/fixtureeditor.pro -o $(MAKEFILE)
sub-fixtureeditor-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) fixtureeditor/ || $(MKDIR) fixtureeditor/ 
	cd fixtureeditor/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/fixtureeditor/fixtureeditor.pro -o $(MAKEFILE)
sub-fixtureeditor: fixtureeditor/$(MAKEFILE) FORCE
	cd fixtureeditor/ && $(MAKE) -f $(MAKEFILE)
sub-fixtureeditor-make_default: fixtureeditor/$(MAKEFILE) FORCE
	cd fixtureeditor/ && $(MAKE) -f $(MAKEFILE) 
sub-fixtureeditor-make_first: fixtureeditor/$(MAKEFILE) FORCE
	cd fixtureeditor/ && $(MAKE) -f $(MAKEFILE) first
sub-fixtureeditor-all: fixtureeditor/$(MAKEFILE) FORCE
	cd fixtureeditor/ && $(MAKE) -f $(MAKEFILE) all
sub-fixtureeditor-clean: fixtureeditor/$(MAKEFILE) FORCE
	cd fixtureeditor/ && $(MAKE) -f $(MAKEFILE) clean
sub-fixtureeditor-distclean: fixtureeditor/$(MAKEFILE) FORCE
	cd fixtureeditor/ && $(MAKE) -f $(MAKEFILE) distclean
sub-fixtureeditor-install_subtargets: fixtureeditor/$(MAKEFILE) FORCE
	cd fixtureeditor/ && $(MAKE) -f $(MAKEFILE) install
sub-fixtureeditor-uninstall_subtargets: fixtureeditor/$(MAKEFILE) FORCE
	cd fixtureeditor/ && $(MAKE) -f $(MAKEFILE) uninstall
etc/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) etc/ || $(MKDIR) etc/ 
	cd etc/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/etc/etc.pro -o $(MAKEFILE)
sub-etc-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) etc/ || $(MKDIR) etc/ 
	cd etc/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/etc/etc.pro -o $(MAKEFILE)
sub-etc: etc/$(MAKEFILE) FORCE
	cd etc/ && $(MAKE) -f $(MAKEFILE)
sub-etc-make_default: etc/$(MAKEFILE) FORCE
	cd etc/ && $(MAKE) -f $(MAKEFILE) 
sub-etc-make_first: etc/$(MAKEFILE) FORCE
	cd etc/ && $(MAKE) -f $(MAKEFILE) first
sub-etc-all: etc/$(MAKEFILE) FORCE
	cd etc/ && $(MAKE) -f $(MAKEFILE) all
sub-etc-clean: etc/$(MAKEFILE) FORCE
	cd etc/ && $(MAKE) -f $(MAKEFILE) clean
sub-etc-distclean: etc/$(MAKEFILE) FORCE
	cd etc/ && $(MAKE) -f $(MAKEFILE) distclean
sub-etc-install_subtargets: etc/$(MAKEFILE) FORCE
	cd etc/ && $(MAKE) -f $(MAKEFILE) install
sub-etc-uninstall_subtargets: etc/$(MAKEFILE) FORCE
	cd etc/ && $(MAKE) -f $(MAKEFILE) uninstall
docs/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) docs/ || $(MKDIR) docs/ 
	cd docs/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/docs/docs.pro -o $(MAKEFILE)
sub-docs-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) docs/ || $(MKDIR) docs/ 
	cd docs/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/docs/docs.pro -o $(MAKEFILE)
sub-docs: docs/$(MAKEFILE) FORCE
	cd docs/ && $(MAKE) -f $(MAKEFILE)
sub-docs-make_default: docs/$(MAKEFILE) FORCE
	cd docs/ && $(MAKE) -f $(MAKEFILE) 
sub-docs-make_first: docs/$(MAKEFILE) FORCE
	cd docs/ && $(MAKE) -f $(MAKEFILE) first
sub-docs-all: docs/$(MAKEFILE) FORCE
	cd docs/ && $(MAKE) -f $(MAKEFILE) all
sub-docs-clean: docs/$(MAKEFILE) FORCE
	cd docs/ && $(MAKE) -f $(MAKEFILE) clean
sub-docs-distclean: docs/$(MAKEFILE) FORCE
	cd docs/ && $(MAKE) -f $(MAKEFILE) distclean
sub-docs-install_subtargets: docs/$(MAKEFILE) FORCE
	cd docs/ && $(MAKE) -f $(MAKEFILE) install
sub-docs-uninstall_subtargets: docs/$(MAKEFILE) FORCE
	cd docs/ && $(MAKE) -f $(MAKEFILE) uninstall
plugins/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) plugins/ || $(MKDIR) plugins/ 
	cd plugins/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/plugins/plugins.pro -o $(MAKEFILE)
sub-plugins-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) plugins/ || $(MKDIR) plugins/ 
	cd plugins/ && $(QMAKE) /mnt/cookiejar/src/ChaosDMX/plugins/plugins.pro -o $(MAKEFILE)
sub-plugins: plugins/$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE)
sub-plugins-make_default: plugins/$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-make_first: plugins/$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-all: plugins/$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-clean: plugins/$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-distclean: plugins/$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-install_subtargets: plugins/$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-uninstall_subtargets: plugins/$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qlc.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		variables.pri \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile qlc.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
variables.pri:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile qlc.pro

qmake_all: sub-engine-qmake_all sub-ui-qmake_all sub-fixtures-qmake_all sub-inputprofiles-qmake_all sub-fixtureeditor-qmake_all sub-etc-qmake_all sub-docs-qmake_all sub-plugins-qmake_all FORCE

make_default: sub-engine-make_default sub-ui-make_default sub-fixtures-make_default sub-inputprofiles-make_default sub-fixtureeditor-make_default sub-etc-make_default sub-docs-make_default sub-plugins-make_default FORCE
make_first: sub-engine-make_first sub-ui-make_first sub-fixtures-make_first sub-inputprofiles-make_first sub-fixtureeditor-make_first sub-etc-make_first sub-docs-make_first sub-plugins-make_first FORCE
all: sub-engine-all sub-ui-all sub-fixtures-all sub-inputprofiles-all sub-fixtureeditor-all sub-etc-all sub-docs-all sub-plugins-all FORCE
clean: sub-engine-clean sub-ui-clean sub-fixtures-clean sub-inputprofiles-clean sub-fixtureeditor-clean sub-etc-clean sub-docs-clean sub-plugins-clean FORCE
	-$(DEL_FILE) debian/*.substvars
	-$(DEL_FILE) debian/*.log
	-$(DEL_FILE) debian/*.debhelper
	-$(DEL_FILE) debian/files
	-$(DEL_FILE) debian/dirs
distclean: sub-engine-distclean sub-ui-distclean sub-fixtures-distclean sub-inputprofiles-distclean sub-fixtureeditor-distclean sub-etc-distclean sub-docs-distclean sub-plugins-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) debian/*.substvars debian/*.log debian/*.debhelper debian/files debian/dirs
install_subtargets: sub-engine-install_subtargets sub-ui-install_subtargets sub-fixtures-install_subtargets sub-inputprofiles-install_subtargets sub-fixtureeditor-install_subtargets sub-etc-install_subtargets sub-docs-install_subtargets sub-plugins-install_subtargets FORCE
uninstall_subtargets: sub-engine-uninstall_subtargets sub-ui-uninstall_subtargets sub-fixtures-uninstall_subtargets sub-inputprofiles-uninstall_subtargets sub-fixtureeditor-uninstall_subtargets sub-etc-uninstall_subtargets sub-docs-uninstall_subtargets sub-plugins-uninstall_subtargets FORCE

test:
	./unittest.sh

sub-engine-check: engine/$(MAKEFILE)
	cd engine/ && $(MAKE) check
sub-ui-check: ui/$(MAKEFILE)
	cd ui/ && $(MAKE) check
sub-fixtures-check: fixtures/$(MAKEFILE)
	cd fixtures/ && $(MAKE) check
sub-inputprofiles-check: inputprofiles/$(MAKEFILE)
	cd inputprofiles/ && $(MAKE) check
sub-fixtureeditor-check: fixtureeditor/$(MAKEFILE)
	cd fixtureeditor/ && $(MAKE) check
sub-etc-check: etc/$(MAKEFILE)
	cd etc/ && $(MAKE) check
sub-docs-check: docs/$(MAKEFILE)
	cd docs/ && $(MAKE) check
sub-plugins-check: plugins/$(MAKEFILE)
	cd plugins/ && $(MAKE) check
check: sub-engine-check sub-ui-check sub-fixtures-check sub-inputprofiles-check sub-fixtureeditor-check sub-etc-check sub-docs-check sub-plugins-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

